//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISBWI.ADODotNet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GISBWIEntities : DbContext
    {
        public GISBWIEntities()
            : base("name=GISBWIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<artikel> artikels { get; set; }
        public DbSet<customsetting> customsettings { get; set; }
        public DbSet<departeman> departemen { get; set; }
        public DbSet<detilpeta> detilpetas { get; set; }
        public DbSet<galeri> galeris { get; set; }
        public DbSet<gambar> gambars { get; set; }
        public DbSet<jenis_artikel> jenis_artikel { get; set; }
        public DbSet<kategori> kategoris { get; set; }
        public DbSet<peta> petas { get; set; }
        public DbSet<privilege> privileges { get; set; }
        public DbSet<service> services { get; set; }
        public DbSet<skpd> skpds { get; set; }
        public DbSet<subnav> subnavs { get; set; }
    }
}
