//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISBWI.ADODotNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class JenisArtikel
    {
        public JenisArtikel()
        {
            this.Artikels = new HashSet<Artikel>();
        }
    
        public int idJenisArtikel { get; set; }
        public string nama { get; set; }
        public Nullable<int> status { get; set; }
        public string keterangan { get; set; }
    
        public virtual ICollection<Artikel> Artikels { get; set; }
    }
}
